### ISSUE TITLE
"cabal install" failed,how to fix it?tks

### ISSUE THREAD

**Issue by luckypoem** [tych0/haggis#5]
hi.

root@AR:/usr/local# git clone https://github.com/tych0/haggis haggis-site
root@AR:/usr/local# cd haggis-site
root@AR:/usr/local/haggis-site# cabal install
Resolving dependencies...
Configuring haggis-0.1.3.0...
Building haggis-0.1.3.0...
Failed to install haggis-0.1.3.0
Build log ( /root/.cabal/logs/haggis-0.1.3.0.log ):
cabal: Entering directory '.'
Configuring haggis-0.1.3.0...
Building haggis-0.1.3.0...
Preprocessing library haggis-0.1.3.0...
[1 of 8] Compiling Text.Haggis.Utils ( src/Text/Haggis/Utils.hs, dist/build/Text/Haggis/Utils.o )
[2 of 8] Compiling Text.Haggis.Types ( src/Text/Haggis/Types.hs, dist/build/Text/Haggis/Types.o )
[3 of 8] Compiling Text.Haggis.Binders ( src/Text/Haggis/Binders.hs, dist/build/Text/Haggis/Binders.o )
[4 of 8] Compiling Text.Haggis.Parse ( src/Text/Haggis/Parse.hs, dist/build/Text/Haggis/Parse.o )

src/Text/Haggis/Parse.hs:63:23:
    Ambiguous occurrence ‘defaultTimeLocale’
    It could refer to either ‘Data.Time.Format.defaultTimeLocale’,
                             imported from ‘Data.Time.Format’ at src/Text/Haggis/Parse.hs:30:1-23
                             (and originally defined in ‘time-1.5.0.1:Data.Time.Format.Locale’)
                          or ‘System.Locale.defaultTimeLocale’,
                             imported from ‘System.Locale’ at src/Text/Haggis/Parse.hs:36:1-20

src/Text/Haggis/Parse.hs:99:65:
    Ambiguous occurrence ‘defaultTimeLocale’
    It could refer to either ‘Data.Time.Format.defaultTimeLocale’,
                             imported from ‘Data.Time.Format’ at src/Text/Haggis/Parse.hs:30:1-23
                             (and originally defined in ‘time-1.5.0.1:Data.Time.Format.Locale’)
                          or ‘System.Locale.defaultTimeLocale’,
                             imported from ‘System.Locale’ at src/Text/Haggis/Parse.hs:36:1-20
cabal: Leaving directory '.'
cabal: Error: some packages failed to install:
haggis-0.1.3.0 failed during the building phase. The exception was:
ExitFailure 1
root@AR:/usr/local/haggis-site#

**Comment by tych0** [comment]
Thanks for the report, I just pushed a fix. Looks like was just a bug because the packages had changed and I hadn't built a new haggis in a while.

**Comment by luckypoem** [comment]
hi.
i recloned your repo,but still "cabal install " failed.howto fix it?
tks.

root@AR:/usr/local/haggis-site# cabal install
Resolving dependencies...
internal error: could not construct a valid install plan.
The proposed (invalid) plan contained the following problems:
Package directory is required by several packages, but they require
inconsistent versions:
package zip-archive-0.3.0.4 requires directory-1.2.7.0
package yaml-0.8.18.1 requires directory-1.2.7.0
package x509-system-1.6.3 requires directory-1.2.7.0
package temporary-1.2.0.4 requires directory-1.2.7.0
package streaming-commons-0.1.15.5 requires directory-1.2.7.0
package pandoc-1.17.2 requires directory-1.2.7.0
package pandoc-1.17.2 requires directory-1.2.7.0
package hslogger-1.2.10 requires directory-1.2.7.0
package haggis-0.1.3.0 requires directory-1.2.7.0
package haggis-0.1.3.0 requires directory-1.2.7.0
package filemanip-0.3.6.3 requires directory-1.2.7.0
package MissingH-1.4.0.1 requires directory-1.2.7.0
package HaXml-1.25.3 requires directory-1.2.7.0
package HaXml-1.25.3 requires directory-1.2.7.0
package process-1.4.2.0 requires directory-1.2.6.2

Package time is required by several packages, but they require inconsistent
versions:
package zip-archive-0.3.0.4 requires time-1.5.0.1
package rss-3000.2.0.5 requires time-1.5.0.1
package random-1.1 requires time-1.5.0.1
package pandoc-1.17.2 requires time-1.5.0.1
package http-client-0.5.1 requires time-1.5.0.1
package hslogger-1.2.10 requires time-1.5.0.1
package haggis-0.1.3.0 requires time-1.5.0.1
package directory-1.2.7.0 requires time-1.5.0.1
package cookie-0.4.2.1 requires time-1.5.0.1
package convertible-1.1.1.0 requires time-1.5.0.1
package aeson-0.11.2.1 requires time-1.5.0.1
package MissingH-1.4.0.1 requires time-1.5.0.1
package HTTP-4000.3.3 requires time-1.5.0.1
package HDBC-2.4.0.1 requires time-1.5.0.1
package unix-2.7.2.0 requires time-1.6.0.1
package directory-1.2.6.2 requires time-1.6.0.1

Proposed plan:
Configured HDBC-2.4.0.1 (.fake.HDBC-2.4.0.1)
Configured HDBC-sqlite3-2.3.3.1 (.fake.HDBC-sqlite3-2.3.3.1)
Configured HTTP-4000.3.3 (.fake.HTTP-4000.3.3)
Configured HUnit-1.3.1.1 (.fake.HUnit-1.3.1.1)
Configured HaXml-1.25.3 (.fake.HaXml-1.25.3)
Configured JuicyPixels-3.2.7.2 (.fake.JuicyPixels-3.2.7.2)
Configured MissingH-1.4.0.1 (.fake.MissingH-1.4.0.1)
Configured SHA-1.6.4.2 (.fake.SHA-1.6.4.2)
Configured aeson-0.11.2.1 (.fake.aeson-0.11.2.1)
Configured ansi-terminal-0.6.2.3 (.fake.ansi-terminal-0.6.2.3)
Configured ansi-wl-pprint-0.6.7.3 (.fake.ansi-wl-pprint-0.6.7.3)
Configured asn1-encoding-0.9.4 (.fake.asn1-encoding-0.9.4)
Configured asn1-parse-0.9.4 (.fake.asn1-parse-0.9.4)
Configured asn1-types-0.3.2 (.fake.asn1-types-0.3.2)
Configured async-2.1.0 (.fake.async-2.1.0)
Configured attoparsec-0.13.0.2 (.fake.attoparsec-0.13.0.2)
Configured base64-bytestring-1.0.0.1 (.fake.base64-bytestring-1.0.0.1)
Configured blaze-builder-0.4.0.2 (.fake.blaze-builder-0.4.0.2)
Configured blaze-html-0.8.1.2 (.fake.blaze-html-0.8.1.2)
Configured blaze-markup-0.7.1.0 (.fake.blaze-markup-0.7.1.0)
Configured byteable-0.1.1 (.fake.byteable-0.1.1)
Configured case-insensitive-1.2.0.7 (.fake.case-insensitive-1.2.0.7)
Configured cereal-0.5.3.0 (.fake.cereal-0.5.3.0)
Configured cmark-0.5.3.1 (.fake.cmark-0.5.3.1)
Configured conduit-1.2.7 (.fake.conduit-1.2.7)
Configured connection-0.2.5 (.fake.connection-0.2.5)
Configured convertible-1.1.1.0 (.fake.convertible-1.1.1.0)
Configured cookie-0.4.2.1 (.fake.cookie-0.4.2.1)
Configured cryptonite-0.17 (.fake.cryptonite-0.17)
Configured data-default-0.7.1.1 (.fake.data-default-0.7.1.1)
Configured data-default-class-0.1.2.0 (.fake.data-default-class-0.1.2.0)
Configured data-default-instances-containers-0.0.1
(.fake.data-default-instances-containers-0.0.1)
Configured data-default-instances-dlist-0.0.1
(.fake.data-default-instances-dlist-0.0.1)
Configured data-default-instances-old-locale-0.0.1
(.fake.data-default-instances-old-locale-0.0.1)
Configured digest-0.0.1.2 (.fake.digest-0.0.1.2)
Configured directory-1.2.7.0 (.fake.directory-1.2.7.0)
Configured dlist-0.8.0.1 (.fake.dlist-0.8.0.1)
Configured enclosed-exceptions-1.0.2 (.fake.enclosed-exceptions-1.0.2)
Configured exceptions-0.8.3 (.fake.exceptions-0.8.3)
Configured extensible-exceptions-0.1.1.4 (.fake.extensible-exceptions-0.1.1.4)
Configured fail-4.9.0.0 (.fake.fail-4.9.0.0)
Configured filemanip-0.3.6.3 (.fake.filemanip-0.3.6.3)
Configured haddock-library-1.4.2 (.fake.haddock-library-1.4.2)
Configured haggis-0.1.3.0 (.fake.haggis-0.1.3.0)
Configured hashable-1.2.4.0 (.fake.hashable-1.2.4.0)
Configured highlighting-kate-0.6.2.1 (.fake.highlighting-kate-0.6.2.1)
Configured hourglass-0.2.10 (.fake.hourglass-0.2.10)
Configured hquery-0.1.1.0 (.fake.hquery-0.1.1.0)
Configured hslogger-1.2.10 (.fake.hslogger-1.2.10)
Configured hslua-0.4.1 (.fake.hslua-0.4.1)
Configured http-client-0.5.1 (.fake.http-client-0.5.1)
Configured http-client-tls-0.3.0 (.fake.http-client-tls-0.3.0)
Configured http-types-0.9.1 (.fake.http-types-0.9.1)
Configured lifted-base-0.2.3.8 (.fake.lifted-base-0.2.3.8)
Configured memory-0.13 (.fake.memory-0.13)
Configured mime-types-0.1.0.7 (.fake.mime-types-0.1.0.7)
Configured mmorph-1.0.6 (.fake.mmorph-1.0.6)
Configured monad-control-1.0.1.0 (.fake.monad-control-1.0.1.0)
Configured mtl-2.2.1 (.fake.mtl-2.2.1)
Configured network-2.6.3.1 (.fake.network-2.6.3.1)
Configured network-uri-2.6.1.0 (.fake.network-uri-2.6.1.0)
Configured old-locale-1.0.0.7 (.fake.old-locale-1.0.0.7)
Configured old-time-1.1.0.3 (.fake.old-time-1.1.0.3)
Configured optparse-applicative-0.12.1.0 (.fake.optparse-applicative-0.12.1.0)
Configured pandoc-1.17.2 (.fake.pandoc-1.17.2)
Configured pandoc-types-1.16.1 (.fake.pandoc-types-1.16.1)
Configured parsec-3.1.11 (.fake.parsec-3.1.11)
Configured pem-0.2.2 (.fake.pem-0.2.2)
Configured polyparse-1.12 (.fake.polyparse-1.12)
Configured primitive-0.6.1.0 (.fake.primitive-0.6.1.0)
Configured process-1.4.2.0 (.fake.process-1.4.2.0)
Configured random-1.1 (.fake.random-1.1)
Configured regex-base-0.93.2 (.fake.regex-base-0.93.2)
Configured regex-compat-0.95.1 (.fake.regex-compat-0.95.1)
Configured regex-pcre-builtin-0.94.4.8.8.35
(.fake.regex-pcre-builtin-0.94.4.8.8.35)
Configured regex-posix-0.95.2 (.fake.regex-posix-0.95.2)
Configured resourcet-1.1.7.5 (.fake.resourcet-1.1.7.5)
Configured rss-3000.2.0.5 (.fake.rss-3000.2.0.5)
Configured scientific-0.3.4.9 (.fake.scientific-0.3.4.9)
Configured semigroups-0.18.2 (.fake.semigroups-0.18.2)
Configured socks-0.5.5 (.fake.socks-0.5.5)
Configured split-0.2.3.1 (.fake.split-0.2.3.1)
Configured stm-2.4.4.1 (.fake.stm-2.4.4.1)
Configured streaming-commons-0.1.15.5 (.fake.streaming-commons-0.1.15.5)
Configured syb-0.6 (.fake.syb-0.6)
Configured tagged-0.8.5 (.fake.tagged-0.8.5)
Configured tagsoup-0.14 (.fake.tagsoup-0.14)
Configured temporary-1.2.0.4 (.fake.temporary-1.2.0.4)
Configured texmath-0.8.6.5 (.fake.texmath-0.8.6.5)
Configured text-1.2.2.1 (.fake.text-1.2.2.1)
Configured time-1.5.0.1 (.fake.time-1.5.0.1)
Configured tls-1.3.8 (.fake.tls-1.3.8)
Configured transformers-base-0.4.4 (.fake.transformers-base-0.4.4)
Configured transformers-compat-0.5.1.4 (.fake.transformers-compat-0.5.1.4)
Configured unix-2.7.2.0 (.fake.unix-2.7.2.0)
Configured unix-compat-0.4.2.0 (.fake.unix-compat-0.4.2.0)
Configured unordered-containers-0.2.7.1 (.fake.unordered-containers-0.2.7.1)
Configured utf8-string-1.0.1.1 (.fake.utf8-string-1.0.1.1)
Configured vector-0.11.0.0 (.fake.vector-0.11.0.0)
Configured x509-1.6.3 (.fake.x509-1.6.3)
Configured x509-store-1.6.1 (.fake.x509-store-1.6.1)
Configured x509-system-1.6.3 (.fake.x509-system-1.6.3)
Configured x509-validation-1.6.3 (.fake.x509-validation-1.6.3)
Configured xml-1.3.14 (.fake.xml-1.3.14)
Configured xmlhtml-0.2.3.5 (.fake.xmlhtml-0.2.3.5)
Configured yaml-0.8.18.1 (.fake.yaml-0.8.18.1)
Configured zip-archive-0.3.0.4 (.fake.zip-archive-0.3.0.4)
Configured zlib-0.6.1.1 (.fake.zlib-0.6.1.1)
PreExisting Cabal-1.24.0.0 (Cabal-1.24.0.0)
PreExisting array-0.5.1.1 (array-0.5.1.1)
PreExisting base-4.9.0.0 (base-4.9.0.0)
PreExisting binary-0.8.3.0 (binary-0.8.3.0)
PreExisting bytestring-0.10.8.1 (bytestring-0.10.8.1)
PreExisting containers-0.5.7.1 (containers-0.5.7.1)
PreExisting deepseq-1.4.2.0 (deepseq-1.4.2.0)
PreExisting directory-1.2.6.2 (directory-1.2.6.2)
PreExisting filepath-1.4.1.0 (filepath-1.4.1.0)
PreExisting ghc-boot-th-8.0.1 (ghc-boot-th-8.0.1)
PreExisting ghc-prim-0.5.0.0 (ghc-prim-0.5.0.0)
PreExisting integer-gmp-1.0.0.1 (integer-gmp-1.0.0.1)
PreExisting pretty-1.1.3.3 (pretty-1.1.3.3)
PreExisting process-1.4.2.0 (process-1.4.2.0)
PreExisting rts-1.0 (rts)
PreExisting template-haskell-2.11.0.0 (template-haskell-2.11.0.0)
PreExisting time-1.6.0.1 (time-1.6.0.1)
PreExisting transformers-0.5.2.0 (transformers-0.5.2.0)
PreExisting unix-2.7.2.0 (unix-2.7.2.0)

CallStack (from HasCallStack):
error, called at ./Distribution/Client/Dependency.hs:658:33 in
main:Distribution.Client.Dependency
root@AR:/usr/local/haggis-site#

**Comment by tych0** [comment]
On Thu, Aug 11, 2016 at 11:15:50PM -0700, luckypoem wrote:
> hi.
> i recloned your repo,but still "cabal install " failed.howto fix it?

Try running `cabal update` to update to the latest hackage deps; I'm
not seeing this problem myself.

**Comment by luckypoem** [comment]
TKS.NOW IT'S OK
